### ISSUE TITLE
Experience what is the best way to test a component

### ISSUE THREAD

**Issue by ismailarilik** [softeria-io/umur-grid-component#23]
Try those:

- [x] Test component with vue-test-utils
- [x] Extract logic in the component to TS files and test those files

And look at these metrics:

- [x] Which one is easier?
- [x] Which one provides more isolation? 
- [x] Which one provides more coverage?

**Comment by Umur-E** [comment]
Testing functions separately requires more unit tests as far as I observed. On the other hand, it provides more isolation and coverage. Thanks to this extraction, I was able to increase my overall coverage above the threshold.
